site_name: Sigi Vilares
site_description: 'Informação com Credibilidade'
site_author: 'Sigi Vilares'

repo_name: '2019.2-SigiVilares'
repo_url: 'https://github.com/Interacao-Humano-Computador/2019.2-SigiVilares'

copyright: 'Copyright &copy; 2019 Sigi Vilares'

theme:
  name: 'material'
  language: 'pt'
  palette:
    primary: 'black'
    accent: 'red'
  logo: 'images/logo.png'
  favicon: 'images/favicon.ico'
  font:
    text: 'Muli'
    code: 'sans-serif'

markdown_extensions:
  - admonition

nav:
  - Início: index.md
  - Planejamento:
    # - Heatmap: planejamento/Heatmap.md
    - Roadmap: planejamento/Roadmap.md
    # - Metodologia: planejamento/Metodologia.md
    - Processo de Design: planejamento/ProcessodeDesign.md
    # - Ponto de Controle: planejamento/PontoDeControle.md
    # - Metas de Usabilidade: planejamento/MetasDeUsabilidade.md
    # - Resultados: planejamento/Resultados.md
  - Avaliação Heurística: avaliacao_heuristica/AvaliacaoHeuristica.md
  - Story Board: story_board/StoryBoard.md
  - Guia de Estilo: guia_de_estilo/GuiaDeEstilo.md
  - Identificação de Necessidades:
    - Perfil do Usuário: identificacao_de_necessidades/PerfilDoUsuario.md
    - Análise de Tarefas: identificacao_de_necessidades/AnaliseDeTarefas.md
    - Características da Plataforma: identificacao_de_necessidades/CaracteristicasDaPlataforma.md
    - Princípios Gerais de Projeto: identificacao_de_necessidades/PrincipiosGeraisDeProjeto.md
    - Planejamento da Avaliação: identificacao_de_necessidades/PlanejamentoDaAvaliacao.md
    - Protótipo de Papel: identificacao_de_necessidades/PrototipoDePapel.md
  # - Protótipo de Alta Fidelidade: ProtótipoDeAltaFidelidade.md
