site_name: Sigi Vilares
repo_name: '2019.2-SigiVilares'
repo_url: 'https://github.com/Interacao-Humano-Computador/2019.2-SigiVilares'

theme:
  name: 'material'
  language: 'pt'

  palette:
    primary: 'deep purple'
    accent: 'deep purple'

nav:
  - Início: index.md